### ISSUE TITLE
Improve Subgraph Query & Valuable Data - Get full DT name and other useful information to ape

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-py#111]
[Poolinfo Data]
Right now the DT_symbol is coming in without it's code-number at the end.
There is other data that we're currently receiving that is just not useful/friendly for DF decision-making (datatoken/pool/basetoken addresses, etc...)

[Improving Data]
- We want to reduce information that is not usesful
- We want to increase engagement/performance data that is useful/friendly (below is just a sample list... KISS + focus on low-hanging fruits)
+ Full DT_symbol
+ Total Staked
+ Number of LPers
+ Number of Token Holders
+ Dataset Human-Readable Name

### DoD:
- Add code-number at end of DT_symbol
- Add other basic stats: NumLP, NumTokenHolders, TotalOceanStaked
- This has been implemented in df-py + df-sql

**Comment by idiom-bytes** [comment]
We need to revisit this as part of the new table.

**Comment by trentmc** [comment]
Obsolete in the face of ve, I believe. Reopen if you see otherwise
