### ISSUE TITLE
Create subgraph for events created by DFRewards.sol

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/df-py#155]
Goal: a complete new subgraph that handle all events created by DFRewards.sol

**Comment by alexcos20** [comment]
for now, let's have a separate one

**Comment by jamiehewitt15** [comment]
So will it be this sub-graph that calls the [price-fetch-server](https://github.com/oceanprotocol/price-fetch-server/) rather the main ocean-subgraph? 

Related issue: https://github.com/oceanprotocol/ocean-subgraph/issues/448

**Comment by trentmc** [comment]
This issue is fairly ambiguous, could you clarify please, @alexcos20 ?

**Comment by alexcos20** [comment]
Closing this, ocean-subgraph has full support of DFRewards (https://github.com/oceanprotocol/ocean-subgraph/pull/531)
