### ISSUE TITLE
Pool Explorer is broken at beginning of each week. App creates a negative UX feedback loop due to backend queries.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-py#198]
The problem:
The current GQL  query filters out datasets that have no DCV and causes a broad range of usage and discovery issues.

Example:
- DF Pool Explorer only consider pools with consume, although they might have great TVL. 
- Pools only show up once consume takes place, which means that at early week the dashboard is empty and many assets are missing
- This causes problems with with production because there are various assets in EWT + other chains w/ TVL, however they cannot be discovered by users.
- Staging is currently barren and not usable as a side effect of this problem.

Towards a solution:
DF Pool Explorer should facilitate the discovery of pools that have both TVL OR DCV
- Pickup all assets from the marketplace, even if they do not have any consume
- Sort them by TVL first, and then consume
- Pools that have TVL but no consume should still be discoverable
- Further: Pool Explorer should for an example feature "Top TVL Gainers" pools, which might not have had any consume at the beginning of the week.

DoD
- [ ] Pool Explorer should facilitate the discovery and browsing of assets so users can more easily farm. This may include items that have TVL but no consume.

**Comment by trentmc** [comment]
@trizin @KatunaNorbert should this issue be in BE v0.1 column, or FE v0.1 column? 

And, please assign & prioritize amongst yourselves accordingly. Thanks!

**Comment by trentmc** [comment]
obsolete
