### ISSUE TITLE
To incentivize publishing, by rewarding publishers as part of DF rewards

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#230]
_Trent [in discord](https://discord.com/channels/612953348487905282/773927370280796241/999592890785337394)_:

We've thought about direct incentives to publish via DF. However the big concern there is rampant publishing if randomly data just for rewards -- kinda useless. That's why DF focuses on rewarding consume, which implicitly includes publishing.

When we do give rewards in DF as a function of consume DVD stake, give eg 25% of those rewards directly to the publisher. What do you think of this idea?

_Moritz response:_

Yes, a cut of the DF to be assigned to the publisher would create an immediate monetary incentive linked to consume volume. The publisher would need do their part in order to receive their cut (without needing to lock up liquidity themselves, which is another consideration for risk assessment).

_Trent response:_

Glad to hear that this idea resonates with you. 

I think we still want to incentivize publishers to lock up liquidity too. Better aligns incentives. As a riff on the idea above: what if publishers simply get a boost on DF rewards if they are the publisher of a given dataset. E.g. 1.5x multiplier.

A related challenge to all these ideas - which is why we never shipped this yet - is fake dataset copies. That is: Molly buys a popular dataset, republishes it for herself, stakes on that, and gets 1.5x more rewards. Then the community's counter to this is to send it to purgatory. Then Molly's  counter to this is to publish last-minute. Then the DF program's counter to this is: dataset must have been live for >1 week. And maybe that will work? (ie purgatory + only start getting rewards 1 week after publish)

**Comment by alexcos20** [comment]
Can we close this?

**Comment by trentmc** [comment]
Yes, we can close this.

Resolution: don't do this. There's too many attack vectors, it gets complicated quickly. 

If publishers want to make money, they make money by (a) selling useful data (b) staking on datasets with consume volume.
