### ISSUE TITLE
Data Explorer + DFVE Metrics - Define metrics to enrich/populate dataNFT rows

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-py#280]
#### Overall Approach
We should expand dfpy, or create additional sql query to serve these metrics.
This data can enrich the Data Explorer UX, to improve allocation & investments.

Candidate Solutions
1. Have our FE writing complex queries (joins, sums, etc...) joining across multiple tables w/ a star schema.
1. We have the BE preparing all of this data/tables ahead of time, making sure it's correct, and ready to consume

I lean towards (2) as certain metrics, aggregations, etc... are better done ahead of time in python, and consumed by the FE via a simple rest api.

I propose we use this ticket to expand on what can be done here, and define the next 3-5 things we're going to deliver.
Improve a bit at a time.

#### Data Explorer Page
- DONE - veOcean locked per dataNFT
- Datatoken Symbol/Name
- Ocean consumed per dataNFT
- Ocean locked per dataNFT
- USD locked per dataNFT
- Last 24h, week, month DCV
- Last 24h, week, month veOCEAN
- Last 24h, week, month est Rewards

#### veOCEAN Page
veMetrics Card:
- veOcean supply, Ocean locked, USD locked est.
- average lock time

#### My meOCEAN card:
veOcean, total voting power, ocean locked, usd est
- rewards claimed
- historical apy / predicted apy
 
#### Claim Rewards Page:
1. Estimated available inside this epoch
1. Estimated rewards from fees (OPC) << fed dynamically into the system, we can't pre-configure/estimate it. Maybe make it "Fees available to claim".
1. Estimated rewards from staking VE (X% of treasury yield) << we can configure/set ahead of time
1. Estimated rewards from allocating VE (Y% of treasury yield) << we can configure/set ahead of time

What we are showing at the moment => Claimable Rewards in Total:
1. feeEstimate.vy (val1) & feeDistributor.vy (val2)
1. DFRewards.vy

### DoD:
- [ ] New schema & table requirements defined
- [ ] Data Flow diagram updated

**Comment by idiom-bytes** [comment]
We might have had a task in the past containing various fields, let's link to that issue

**Comment by idiom-bytes** [comment]
@trizin i tried to separate and number them, maybe we can talk about these more in detail

**Comment by idiom-bytes** [comment]
Calculate last value from Subgraph => get price from Binance/Coingecko => convert the basetoken to USD

According to Alex, this should be good enough for now.

**Comment by idiom-bytes** [comment]
In the end, this ticket should help define the overall update & requirements for schema, csvs & tables (df-py and df-sql)

Schema/Tables Improvements - Datatoken symbol + name
Workflow Improvements - Historical data (not just the week)
ETL/Summary Improvements - Aggregate/Summary metrics (not time series, or from contract)

Some of these will be higher priority, R:R than others. Focus on high R:R first.

**Comment by idiom-bytes** [comment]
Additionally, how to improve Data Explorer:

Candidate Solution A:
1. Move all allocation related elements to right
2. Move all column/dfsql elements to the left
3. Make more room for dfsql data + explain somewhere that this is the data that updates every 5 minutes
4. Change styling for objects on right, especially "My Allocation". This works with the datasets, but it does not update the data from dfsql.

Even if we cache it locally and modify those values, there could be 1 million veOCAN in a data asset and the user would not be able to tell how much (percent) they have allocated to the asset. By changing the styling of the "My Allocation" column, we can visibily communicate how the user is allocating their veOCEAN. 

Candidate Solution B:
- Create a separate column that shows "MyVeOCEAN vs. Global veOCAN" (I believe this is rendundant.

![Screenshot from 2022-09-29 14-12-02.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/67586bf9-843b-4b4f-9ff0-0260ef8938c7)

**Comment by idiom-bytes** [comment]
Please see https://github.com/oceanprotocol/df-web/issues/297 for more feedback on what we can add to this tables/data so we can serve richer context for the user

**Comment by idiom-bytes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE--DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-py/280?planning-poker) with Zenhub @KatunaNorbert @trizin

**Comment by idiom-bytes** [comment]
Additional metrics to potentially track. Where do these go?

**Aggregate:**
- Total number of unique publishers/consumers/stakers
- % of Ocean staked
- Increase in total Ocean volume from rewards

**Specific:**
- Which wallets received the most rewards

**Historically per week**
- What data assets did they stake on
- What % of rewards did top 5 wallets receive
- Average amount of Ocean/total crypto held per wallet
- % of Ocean staked
- Which data sets received the most rewards

**Per week**
- What was the DCV on them per week
- Number of unique buyers

Mixing information with Acquaris info to see data around the topics of the datasets

**Comment by alexcos20** [comment]
> Total number of unique publishers/consumers/stakers
source:  subgraph, but nice to have additional aggregation on backend

> % of Ocean staked
source: subgraph

> Increase in total Ocean volume from rewards
not sure what you mean

> Which wallets received the most rewards
Already available in df-sql, a simple sum could be exposed by an api

> What data assets did they stake on
Already available in df-sql

> What % of rewards did top 5 wallets receive
Already available in df-sql

> Average amount of Ocean/total crypto held per wallet
Source:  etherscan api, but would need additional aggregation on backend

> % of Ocean staked
source: subgraph + web3.balanceOf

>Which data sets received the most rewards
Could be exported by df-py and stored in df-sql


> What was the DCV on them per week
Could be exported by df-py and stored in df-sql

> Number of unique buyers
Source: subgraph, but nice to have additional aggregation on backend

One quick way to get more stats would be that instead of importing rewardsperlp-OCEAN.csv from df-py, we could import rewardsinfo-OCEAN.csv which has more lines, and aggregate them

**Comment by idiom-bytes** [comment]
```Increase in total Ocean volume from rewards```
A chart showing how passive, and active rewards are growing over time.

```One quick way to get more stats would be that instead of importing rewardsperlp-OCEAN.csv from df-py, we could import rewardsinfo-OCEAN.csv which has more lines, and aggregate them```

rewardsperlp is an aggregate of rewardsinfo (sum per LP)

**Comment by trentmc** [comment]
Partly done via autobots & ocean stats

For anything remaining: Given Predictoor, DF Challenge, DF Predictoor: this is super-low priority, and will look different when revisited. And we have _way_ too many issues. So closing this.
