### ISSUE TITLE
Test filtering out nonMarketAssets from query_all function 

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-py#293]
From PR => https://github.com/oceanprotocol/df-py/pull/292
- [ ] We should find a way to test the filtering of non-market assets in the query_all function by perhaps leveraging Aquarius in the barge. We will also need to "register" all generated assets to Aquarius in other tests that use query_all. Or perhaps we could mock getAquariusAssetNames function.
- [x] I need to learn if there is a limit for the Aquarius endpoint. If that's the case, I'll adjust the batch size.
- [ ] It's hard to test a full flow. I can test the filter function, but the aquarius testing part is hard to complete.

**Comment by idiom-bytes** [comment]
Berkay: we need to use aquarius, it's currently not using barge, we need to create functions to execute this, there is more work than meets the eye.

Trent: It probably uses aqua, if we do, it's copy paste code from df-py reading aquarius. But if this ends up being wrong, it could be as simple as seeing what aquarius follows, and do the same. Basically, everything that has a DDO and it's not in purgatory.

**Comment by trentmc** [comment]
We have near end-to-end tests via test_end_to_end.py, though not fully.

This is good enough for now. Doing a more macro thing will take more effort, and hurt runtime a lot.
