### ISSUE TITLE
Add more tests for veFeeEstimate

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/df-py#300]
Today we might have found a bug in veFeeEstimate, which lead to inconsistent value coming from veFeeEstimate vs claiming rewards.
Let's add more tests for veFeeEstimate, that will use a couple of weeks of testing (locking tokens, checkpoint, advance one week, compare feeEstimate to whatever value is actually claimed)

**Comment by idiom-bytes** [comment]
@alexcos20 can you please give this a thumbs up or thumbs down w/ your requirements? 

I believe this task may be completed.
