### ISSUE TITLE
barge + veAllocate does not work with df-web

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-py#320]
### Problem:
When connecting df-web to the default barge deployment contract for veAllocate, we get repeated JSON-RPC errors.

To get around this, I configure df-py w/ a ganache PK and deploy a new veAllocate contract using `dftool newVeAllocate 8996`, retrieve this new veAllocate contract 0x => df-web .env configuration => I can now use df-web to allocate my veOCEAN.

### DoD:
- [ ] The default barge deployment should include a veAllocate contract that can be interacted with by df-web

**Comment by alexcos20** [comment]
see slack
