### ISSUE TITLE
Publish each DF week's csvs as a data asset

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#35]
**Motivations:** 
- it's easy
- Ocean data science community will love to play with this 
- And it's cool assets to have in Ocean ecosystem:)

**On implementing**

Pre-requisite: already have a GFolder to store all data. One subfolder for each week. New dftool command to add another week's worth of data to GFolder

Then, to implement: 
- [ ] (one-time) Publish an Ocean data asset into Ocean Market

That's it. The previously-created dftool command does the weekly thing

**Comment by w1kke** [comment]
Indeed - would love to see the csv from week 1.
