### ISSUE TITLE
Bisection search causes inconsistency in DCV values

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#363]
### Background / Motivation

We're using bisection search to find start and end block numbers for the DF week in the networks other than ETH mainnet. As these numbers are not 100% consistent between different runs we might get different results.

There are two possible paths:
- (a) Specify a tolerance level, that's say 1/00 of a cent worth of OCEAN. Eg 0.0001 OCEAN
- (b) Specify a tolerance level that's within Solidity's or Python's numerical precision

Roughly, I'm ok with either. And, (b) is less risky so I recommend it, unless it's too slow.

We should be able to readily get these numbers consistent within a target tolerance level

### TODOs

My suggestion to proceed: (highest level: go for b first, and if needed go for a)
1. Write unit tests that expose the inconsistency
2. Update the unit tests to allow a target tolerance
3. Update bisection code to hit target tolerance
4. If needed, update other code to allow the target tolerance too

**Comment by idiom-bytes** [comment]
I think this is fixed due to the new implementation to get blocks.
@trizin can we close this issue?

**Comment by trentmc** [comment]
There are two possible paths:
- (a) Specify a tolerance level, that's say 1/00 of a cent worth of OCEAN. Eg 0.0001 OCEAN
- (b) Specify a tolerance level that's within Solidity's or Python's numerical precision

Roughly, I'm ok with either. And, (b) is less risky so I recommend it, unless it's too slow.

We should be able to readily get these numbers consistent within a target tolerance level

My suggestion to proceed: (highest level: go for b first, and if needed go for a)
1. Write unit tests that expose the inconsistency
2. Update the unit tests to allow a target tolerance
3. Update bisection code to hit target tolerance
4. If needed, update other code to allow the target tolerance too

**Comment by trentmc** [comment]
> #793
> 
> This PR verifies that the identified block number is within a 15-minute range of the target timestamp. Throws an error otherwise.

@trizin do you see an opportunity to "Update bisection code to hit target tolerance"? Eg by simply tightening the target tolerance, without making runtimes much longer?

**Comment by trentmc** [comment]
> Imo, the most reliable solution to mitigate these is maintaining a record of the start and end blocks for a given week (week x). For the subsequent week (week x+1), the starting block should be set as the ending block of the previous week (week x).

Where are the candidate places that we would store the record of start & end blocks for a given week? What do you recommend. If this is reliable and repeatable, that sounds like a good choice. (Ocean Data NFT with ERC721?)

**Comment by trentmc** [comment]
> > Ocean Data NFT with ERC721
> 
> Sounds brilliant! I'd propose deploying on Polygon Mainnet, it'd cost us 1 tx/week (probably around 0.01-0.03 MATIC)

Works for me.

[Here's the README](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/key-value-public.md) in ocean.py for set/get on ERC721. But you don't need an ocean.py dependency, instead, just use its [implementation](https://github.com/oceanprotocol/ocean.py/blob/68e0f969307d790769848848033a4cf15209c1e3/ocean_lib/models/data_nft.py#L299) as input to doing it directly.

**Comment by trentmc** [comment]
Obsolete, because we've retired Passive DF & Volume DF
