### ISSUE TITLE
Create route/feed for allocations in purgatory.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-py#366]
### Problem:
Right now, there is no way to view the items in purgatory that the user has allocated to.
This keeps the user from being able to adjust or reset their allocation.

### Candidate Solutions
Cand A
- Show items from purgatory where the user has allocated to, and force them to reallocate
- Users should then be able to reallocate away from these assets, and call "Update Allocations" once

Cand B
- Do not show items from purgatory, but create a "Reset Allocations" button that enables the user to reset their allocations
- This requires 2 txs to reset. 1 for the reset. 2 for the allocation.

### DoD:
- [ ] BE is able to get required purgatory + allocation data in order to show to user, and have them reallocate

**Comment by trentmc** [comment]
This is created as a df-py issue. Did you mean to make it df-web? @idiom-bytes 

FYI here's how df-py sees what's in purgatory (from [query.py)](https://github.com/oceanprotocol/df-py/blob/b9f4f5535218174d46a90b37f40cd80955b3010a/util/query.py#L561). Note that it doesn't use subgraph, it just grabs raw data from a url in github. This means that df-web shouldn't need df-py in the loop at all. Just use the same trick, grabbing the raw data from github.

```python
def _didsInPurgatory() -> List[str]:
    """
    @description
      Return dids of data assets that are in purgatory

    @return
      dids -- list of str
    """
    url = "https://raw.githubusercontent.com/oceanprotocol/list-purgatory/main/list-assets.json"
    resp = requests.get(url)

    # list of {'did' : 'did:op:6F7...', 'reason':'..'}
    data = json.loads(resp.text)

    dids = [item["did"] for item in data]
    return dids
```

**Comment by idiom-bytes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE--DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-py/366?planning-poker) with Zenhub @KatunaNorbert

**Comment by idiom-bytes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE--DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-py/366?planning-poker) with Zenhub @trizin

**Comment by idiom-bytes** [comment]
It's fantastic that this work has moved forward in the backend, but it's not ready to be implemented into FE.
I'm making this note so we can get the BE + FE work separated, and prioritize the FE work accordingly.
