### ISSUE TITLE
Sampling causes allocation amount to be incorrect

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#373]
If the user allocates to asset A and after one day moves that allocation to asset B:

Day 1: Allocate 100 veOCEAN to asset A
Day 2: Re-allocate 100 veOCEAN to asset B

Day 3: df-py shows 50% to A and 50% to B
Day 4: df-py shows 33.3% to A and 66.6% to B
Day 5: df-py shows 25% to A and 75% to B
Day 6: df-py shows 20% to A and 80% to B
Day 7: df-py shows 16% to A and 84% to B

Day 7 - midnight: df-py shows 14% to A and 86% to B

**Comment by trentmc** [comment]
Looks correct to me.

What's the concern?

**Comment by trentmc** [comment]
Thanks for clarifying. Well this isn't a df-py issue, it's a df-web issue.

**Comment by trentmc** [comment]
Thanks for clarifying. 

First - this isn't a df-py issue, it's a df-web issue. df-py is doing exactly as expected.

df-web could simply calculate as if it's midnight. Then problem solved, right?

**Comment by trentmc** [comment]
> entire allocation rather than the sampled one

If you want the "entire allocation" then you need to get the allocation on every single block. In one week, at 12 s per block, that's 50000 blocks.

Even if you have "entire allocation", then the same problem exists.

What the user is looking for -- and therefore df web wants -- is the allocation, as if things don't change between "now" and Thursday midnight.

**Comment by trentmc** [comment]
> What the user is looking for -- and therefore df web wants -- is the allocation, as if things don't change between "now" and Thursday midnight.

So then the questions are:
- how can we get df-py to produce this info ?
- and then pass it on to df-web to use?

**Comment by KatunaNorbert** [comment]
As @trizin just providing an extra value for not-sampled data.
If a user has 20% of allocations on an asset then just add 20% of his veOCEAN instead of adding the sampling part.

**Comment by KatunaNorbert** [comment]
> @KatunaNorbert it makes sense, my concern is; wouldn't it still be a problem that sampled data changes during the week and it might be confusing for users if we have two values.

Well that's the most transparent and explanatory as we could get. We could show them inside the same column side by side, emphasise the not-sampled data so user see that his allocations have moved over and also show the sampled allocation.

I assume the users want a real time asset allocation metric, so the know where the allocations move and can make their strategy based on that. If we show the sampled data they don't get that, they will see the complete allocation shift only by the beginning of the next round.

**Comment by KatunaNorbert** [comment]
I sill think we should display (a).

1.This way it's signalling the user his allocations have been reallocated, but it takes time due to sampling.
2.This is our main metric along side volume that users can use to reallocate and increase their gain.

**Comment by trentmc** [comment]
Doing (a) in addition to (b) is fine. It should be easy enough to compute.

We just want to avoid doing (c) unless really needed, because of the additional complexity. And we don't really need, imo.

**Comment by trentmc** [comment]
> Perhaps instead of having two columns, we could add a toggle two switch between real time 

Two columns means that users can more easily compare the values, which in turn will help their mental model to better understand what each value means. 

Therefore I recommend two columns. (And: make it two actual columns, not just one column with two values, so that they are sortable).

**Comment by KatunaNorbert** [comment]
I agree
