### ISSUE TITLE
Automate active reward distribution in GH Actions

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#387]
Automate active reward distribution in GH Actions.

Workflow Steps:
- Run tests
- Calculate rewards
- Submit txs to multisig

**Comment by idiom-bytes** [comment]
All of these updates are valuable and meaty.
But I worry there are a lot different threads going on.

I know this is now in progress but it's not quite attached to an epic or goal.

I would just like to take some more stuff to completion, before starting more (don't get me wrong, I would love to see this get shipped before you leave on vacay). 

Can we narrow down some of the things that are pending and see if there are any loose strings to tie off?
