### ISSUE TITLE
Passive Rewards - Historical rewards (per round + per user) 

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-py#397]
### Problem
- We do not have this data calculated because we just distribute the rewards towards FeeDistributor.vy
- For us to display historical passive APY data, we need to get this calculated
- df-web #430 is blocked as a result

### Constraints:
- We can't calculate these numbers effectively off-chain
- We may need to calculate these at the contract level or compute & dump this into a csv.
- We are probably gonna have to solve these at the contract level first, in order to get an answer.

### Calculation
- We have the vebals for each user.
- We know how much ocean is going to be distributed as passive reward.
- Therefore, we know the APY.
- This should give us how much OCEAN each LP gets.
- Because we know the reward amount (predefined value) and we know the locked amount (total OCEAN) we can calculate the apy.

*** We may need to investigate how this gets pro-rated by day, and calculated, to make sure we can arrive at the same pro-rated rewards.

### DoD:
- [ ] Our backend/sql now serves historical passive rewards per round + account

**Comment by trentmc** [comment]
Given Predictoor, DF Challenge, DF Predictoor: this is super-low priority, and will look different when revisited. And we have _way_ too many issues. So closing this.
