### ISSUE TITLE
(maybe) Two branches: `release` and `development`. 

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-py#435]
### Background / motivation

Parent epic: [df-py#589](https://github.com/oceanprotocol/df-py/issues/589) "Make auto active rewards reliable". Reliability < 50%. It has several complementary tools.

One candidate tool is: two branches: `release` (main) and `development`

That's the aim of _this_ issue.

But first, we need to decide if we _want_ this. 
- It has a big negative: it hurts DX a lot. That's why we explicitly don't have it in other repos
- Recommend: to the "for-sure" items in the epic first. Namely, improve the CI. Only once those are done, do we decide whether to do this.

### Solutions

(If we do this)
1. We should apply a github flow release methodology (the same methodology we use everywhere else) to have a stable branch.
2. We should configure the scheduled GH actions to use this branch
3. We should start using github flow to improve our dev->staging->production releases
4. We should deprecate `stable-branch-dispense` branch

### DoD:
- [ ] Production branch and release workflow has been configured
- [ ] GH Actions for Passive & Active rewards has been configured to use production branch
- [ ] `stable-branch-dispense` branch is deprecated

**Comment by trentmc** [comment]
Closing because largely redundant with new versioning work (df-py now has versioning)
