### ISSUE TITLE
Switch to new barge

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#438]
### Background / motivation

A few weeks ago, we switched to an old barge branch because the new barge branch broke things. 

In test.yml, this section:
```text
      - uses: actions/checkout@v2
        name: Checkout Barge
        with:
          repository: "oceanprotocol/barge"
          path: "barge"
          ref: 9cc3a9342a47857a0495309e787462d6c60979e6
```

The workaround was to add the bottom line ("ref: 9cc..."). That came in on commit https://github.com/oceanprotocol/df-py/commit/a098c5a305498d75f699bc99620f4804f9d9be56, for issue https://github.com/oceanprotocol/df-py/pull/406

### TODOs

Aim of this issue: 
- switch to new barge. How: change one line in test.yml to "main"
- get tests passing. This may be a challenge, as we've found that new barge is causing tests to hang. [See experiments here](https://github.com/oceanprotocol/df-py/pull/432#issuecomment-1381670193).

**Comment by alexcos20** [comment]
See https://github.com/oceanprotocol/df-py/issues/437#issuecomment-1383615943.
I don't think that new barge is to blame, you will have same results with both versions

**Comment by trentmc** [comment]
> I don't think that new barge is to blame, you will have same results with both versions
The data speaks otherwise.

[Here's](https://github.com/oceanprotocol/df-py/pull/432#issuecomment-1382380218) a CI run with new barge. It fails (it hangs, and more).

Then with a [switch to old barge](https://github.com/oceanprotocol/df-py/pull/432/commits/06b475d89aa01b9e2c3006eb36720ee8d426e641)...

[Here's](https://github.com/oceanprotocol/df-py/pull/432#issuecomment-1382715666) the CI run with old barge. It no longer hangs. (It still fails on Aquarius, but that's another issue.)

You can test for yourself if you like.

**Comment by trentmc** [comment]
Updates: 
- priority of this issue is now higher, because we need newer barge for new Predictoor contracts
- in [PR#542](https://github.com/oceanprotocol/df-py/pull/542), I did negligible changes to simply trigger CI. It passed.
- in [PR#541](https://github.com/oceanprotocol/df-py/pull/541), I switched to new barge, ie main branch. CI failed.

@calina-c can you get to the bottom of this please?

**Comment by trentmc** [comment]
Maybe related: #421: CI fails with "KeyError: development". Barge issue?
