### ISSUE TITLE
Rewards should point from creator => owner

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-py#469]
If we release as is, the status quo remains.

Let's focus on the fix and try to get this ready for DF23
Build on top of updates for https://github.com/oceanprotocol/df-py/pull/468

:hands_up:

### DoD:
- [ ] df-py is processing all information around owner, not creator

**Comment by alexcos20** [comment]
Code is already using "owner", but variables are named "creator". So it's just cosmetic, no impact
