### ISSUE TITLE
Allocations.csv needs to communicate isowner

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#486]
### Requirements:
- [ ] Add a new field "isowner" bool.
- [ ] Add a new field "allocation bonus" field that reports the 2x stake bonus

***All calculations, bonuses, and information from the rules of DF, should be generated inside of df-py

### DoD:
- [ ] On the allocations.csv file, we're going to add a new column "isowner"

**Comment by idiom-bytes** [comment]
We went into DF25 knowing some data could be lost, let's get this implement and launched for Df26.

**Comment by idiom-bytes** [comment]
@trizin how's progress on this?

**Comment by idiom-bytes** [comment]
Looked to help in a couple of different locations. Will review.

**Comment by idiom-bytes** [comment]
@jamiehewitt15 please review what happened, and let's get this shipped. I'll help too.
When we have this ready, let's clean up docs/data availability info, so we can present to FE/iterate wtih them.

**Comment by idiom-bytes** [comment]
To finish this:
- We need to decide how publsiher rewards will be displayed in CSV: could be an ammount, a percentage, whatever.

**Comment by idiom-bytes** [comment]
To finish this:
- We need to decide how publsiher rewards will be displayed in CSV: could be an ammount, a percentage, whatever.

**Comment by jamiehewitt15** [comment]
> @jamiehewitt15 please review what happened, and let's get this shipped. I'll help too. When we have this ready, let's clean up docs/data availability info, so we can present to FE/iterate wtih them.

Is this the right PR https://github.com/oceanprotocol/df-py/pull/487? Looks like it is still in draft with the tests failing

**Comment by idiom-bytes** [comment]
We're closing this because we have publisherRewardAmount.
We do not want to break DRY rules.

**Comment by idiom-bytes** [comment]
We're closing this because we have publisherRewardAmount.
We do not want to break DRY rules.
