### ISSUE TITLE
Integrate shell scripts into df-py and re-write them as py submodules

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-py#492]
### Problem
We have shell scripts outside of the repo, and they are written in bash.

### Solution
They should be integrated into the library and re-written in python.
- [gen_hist_data.sh](https://github.com/oceanprotocol/df-py/blob/main/scripts/gen_hist_data.sh). More info: [df-py#396]
- all.sh
- nftinfo.sh

Related: [df-py#491](https://github.com/oceanprotocol/df-py/issues/491) has more discussion on test coverage.

### DoD:
- [ ] Submit shell scripts from VM
- [ ] Scripts have been written as dftool commands in py
- [ ] Scripts offer test coverage
- [ ] GHA and any other system are using the latest py commands

**Comment by trentmc** [comment]
Made high priority because our CI around active rewards is abysmal. Symptom: reliability of active rewards successfully running on a given week is <50%. 

Doing this will help a lot.

**Comment by trentmc** [comment]
And they're already low priority in zenhub board https://app.zenhub.com/workspaces/data-farming-60ddbf267dd0b500137f3c3d/board

**Comment by trentmc** [comment]
We're not doing this, because Passive DF & Active DF have been retired
