### ISSUE TITLE
Fix dftool commands to use snake_case

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-py#505]
### Problem:
- [x] There are bunch of inconsitencies in dftool command names. Fix them so they are using snake_case and consistent.
- [ ] VM, GHA, and other flows could be impacted by this. We do not want to break things at the same time.
- [ ] Let's hold on this one (i.e. think of a point releases perhaps)

### DoD:
- [ ] Figure out when/how to proceed.
- [ ] Use this format from here on out.

**Comment by trentmc** [comment]
Redundant with #618 which is more general, so closing this
