### ISSUE TITLE
Fix potential bugs caused by delegation calculations

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#527]
Fix potential bugs caused by delegation calculations. 

Some of the potential bugs could be: delegation not applying, the delegation amount is miscalculated.

Test and verify that the calculations are working as expected.

**Comment by trentmc** [comment]
Is this fixed now, via the changes you'd make in https://github.com/oceanprotocol/df-py/pull/574 , @trizin ?

**Comment by trentmc** [comment]
Closed because no issues found over many months. If issues pop up then we will create a new github issue.
