### ISSUE TITLE
Fix warning: DeprecationWarning: abi.decode_abi() --> abi.decode()

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#549]
### Background / motivation

From CI, example warnings:

```text
=============================== warnings summary ===============================
...
util/test/test_oceanutil.py: 13 warnings
util/test/test_query.py: 75 warnings
util/test/veOcean/test_allocate_dt.py: 2 warnings
  /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/eth_abi/codec.py:191: DeprecationWarning: abi.decode_abi() is deprecated and will be removed in version 4.0.0 in favor of abi.decode()
    warnings.warn(

util/test/test_oceanutil.py: 20 warnings
util/test/test_query.py: 125 warnings
util/test/veOcean/test_allocate_dt.py: 4 warnings
  /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/eth_abi/codec.py:164: DeprecationWarning: abi.decode_single() is deprecated and will be removed in version 4.0.0 in favor of abi.decode()
```

[Full example log](https://github.com/oceanprotocol/df-py/actions/runs/4915629331/jobs/8778343603?pr=537)

Priority to fix: soonish, since these warnings obfuscate real issues, and are low effort to fix

### TODOs

Options:
1. It's not our code, so suppress the warnings. 
2. Rather than do the high-level call from tests that triggers calls to `abi.decode_abi()` and `abi.decode_single()`, do a different high-level call
3. Do a PR into brownie to (a) replace calls to `abi.decode_abi()` with `abi.decode()` and (b)  `abi.decode_single()` with `abi.decode()`

Analysis: 3 we can't rely on, 2 might be painful, 1 is simple. Go with 1

**Comment by calina-c** [comment]
These usages are not from our code :) They are from the `eth_abi` package.

**Comment by trentmc** [comment]
Let's suppress the warnings then.
