### ISSUE TITLE
CI fails: Workflow file has syntax error

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#566]
### Background / motivation

The CI run with [this log](https://github.com/oceanprotocol/df-py/actions/runs/4944018629/workflow) failed.

Problem presented:
![issue](https://github.com/oceanprotocol/df-py/assets/5305452/e86b9155-48ec-4660-9bc7-a29af71c9e8e)

**Comment by trentmc** [comment]
Github blame on file in Q: https://github.com/oceanprotocol/df-py/blame/issue566-syntax/.github/workflows/test.yml

The commit with the error: https://github.com/oceanprotocol/df-py/commit/11b6c2f320d34cdffe1368a3e77e8c0196cdb57d

**Comment by alexcos20** [comment]
Nop, it was introduced [here](https://github.com/oceanprotocol/df-py/commit/2b18055fdf28d219d0ff4f412e6cc37dc1f77057)
