### ISSUE TITLE
challenge_data uses Binance, which won't work for US

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#592]
### Background / motivation

[This line](https://github.com/oceanprotocol/df-py/blob/32e6240f9e4f81b31e3ae39c712d3d323e8a358a/util/challenge/judge.py#L126) in df-py's util/challenge/judge.py uses Binance to grab price data. (Via a commit from May 17).

However:
- Binance CEX data endpoint isn't available in USA. Kraken is. 
- Even if our CI isn't in USA, we have an additional constraint: some competitors of predict-eth-challenge may be in USA. Accordingly, that repo's main6.md uses Kraken
- Therefore, df-py needs to use Kraken too

### TODO for this issue

- [ ] Switch back to Kraken
- [ ] Make sure it works! Including: don't just request the most recent data, rather, request data from a "since" starting date. That works for Binance, I wasn't sure Kraken.

**Comment by calina-c** [comment]
It seems it works exactly the same https://github.com/ccxt/ccxt/blob/870202441530547afbfdb7c7ed46c889f2bb6c5e/python/ccxt/async_support/kraken.py#L832
