### ISSUE TITLE
Create specific directories for volume DF, predictoor DF, challenge DF

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/df-py#617]
originally referenced here:

              Re the new directories:
- for _this_ issue just move the new predictoor DF-related queries into df-util/predictoor/query.py
- and create a new issue for the rest

_Originally posted by @trentmc in https://github.com/oceanprotocol/df-py/pull/611#discussion_r1209101614_

(NOT: "We should move all raw graphql queries to separate files, for maintainability and readability. They should be grouped under /queries and possibly their purpose, i.e. queries/predictoor_data.py etc. When used, just import them and add the parameters."

**Comment by trentmc** [comment]
To be clear: I'm not proposing having a separate file for _raw_ queries. 

Rather, I'm proposing:
- have a file util/volume/query.py for volume DF queries. This is the bulk of what current util/query.py has. It should have raw queries _and_ higher-level functions like it currently has.
- have a file util/predictoor/query.py for queries related to predictoor DF. It includes both raw queries and higher-level functions.
- have a file util/challenge/query.py for .. challenge DF.

**Comment by trentmc** [comment]
I just updated the file subject and description accordingly.

The key thing is: separate directories for the 3 substreams of DF. All functionality per substream in each directory. (Vs a special directory just for queries, NO to that)
