### ISSUE TITLE
Concern: do duplicate records in challenge data csv cause any downstream issues?

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#693]
In round 48 challenge data csv, there were duplicate records wrt submitter address.

Note: an address can submit as many predictions as they like. Only the most recent one (that still meets the deadline) is used. The code to calculate winners already handles this.

Also note: there's value for submitters to know that each of their predictions actually made it in.

Discussion: we're actually ok downstream. So no issues

**Comment by trentmc** [comment]
> An address can submit only one prediction, so that's a bug.

This is incorrect. An address can submit as many predictions as they like. Only the most recent one (that still meets the deadline) is used. The code to calculate winners already handles this.
