### ISSUE TITLE
Challenge DF (a) can only handle <= 100 nft transfers, (b) CEX prices are off

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#694]
Issues:
- it takes only 100 nft transfers.   This round had more than 1000
- CEX prices are off

Details: [AlexC in slack](https://oceanprotocol.slack.com/archives/C03L5JZRJ94/p1692249605105419)

**Comment by trentmc** [comment]
What is the specific issue? Please update the description accordingly, and be precise.

Why:
- I can assess whether it's _actually_ an issue
- I can assess whether the PR solves the issue
- It's much better provenance for issues and commits, to speak to our future selves and other devs
- It's good practice, for all the reasons above. We should always make descriptive issues and PRs.
