### ISSUE TITLE
Challenge DF (a) nmse measure is too low. And (b) concern that not profit-oriented

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-py#696]
### Issue (a)

For a given submission, if I look at plots of predicted vs actual, it can qualitatively look way off. But nmse values are still on the order of 1e-6 to 10e-6. Whereas they should probably be around 0.1 - 0.5.

It's scaling the values too much.

But do note it still computes the winners correctly, because scaling doesn't affect the rank-order of winners.

We've known this for a while. It hasn't been a priority to fix, because we still compute winners correctly.

However the DF frontend does report nmses, it's gonna be confusing. So the priority is higher than before.

### Potential issue (b)

And, there's a potential second issue: nmse itself doesn't capture profitability well. 

### Options

1. fix both "(a) nmse measure is too low" _and_ "(b) concern that not profit-oriented"
2. fix just "(a) measure is too low"

### TODOs

- [x] Decide which option, 1 or 2. See comments below. [Decided on 2. Since no objection to that]
- [x] Build it
- Update historical data such that these (new) nmses are reported instead --> moved to [#73](https://github.com/oceanprotocol/df-py/issues/703)

### Appendix

Refs: [slack discussion](https://oceanprotocol.slack.com/archives/C03L5JZRJ94/p1692261664308719)

**Comment by alexcos20** [comment]
There is big difference in computing averages and financial trade.
With the current formula, it only takes into account the difference.  

Example:
User1:    1800,1804
User2:    1798 , 1800
Cex prices:  1799,1802

both users will have the same nmse , but if you trade with user1's data, you will have some profit. With user2, you have a loss.

Proposal for formula:
 - for each candle, try to compute the actual profit. 
 - - If price is > than previous candle, then simulate a buy and calculate profit
 - - If price is < than previous candle, then simulate a sell and calculate profit

Use accumulated profit(or loss) as a baseline for judge

**Comment by trentmc** [comment]
@alexcos20 thank you, I will take this into consideration when I work on it. 

And I will increase the priority, given your comments here and in slack.

**Comment by trentmc** [comment]
> [Alex] There is big difference in computing averages and financial trade.
> With the current formula, it only takes into account the difference.
...
> Proposal: .... Use accumulated profit(or loss) as a baseline for judge

I thought more about this. 

The description has been updated to have , we have two options:
1. fix both "(a) nmse measure is too low" _and_ "(b) concern that not profit-oriented"
2. fix just "(a) measure is too low"

Datapoints:
- The goal is of Challenge DF is to onboard people into being Predictoors. 
- If Challenge DF is too much friction to get going with, they simply won't start
- AI/ML people are used to minimizing error (nmse or similar). Most of their training algorithms are around this. If we ask them to optimize for something else, it greatly shrinks their toolbox, in many cases needing 10x more effort just to get going
- Predictoor itself rewards predictoors for accuracy, not accumulated profit or loss
- If we _did_ ship this, we'd have to communicate this and explain. Not huge effort, but not negligible either. Predictoor needs to be our focus
- Because Challenge DF is just a path to Predictoor, we shouldn't spend too much of S3 time on it (or Ocean DF rewards budget). Currently 5000 OCEAN, perhaps even lower in the future 
- Not doing (b) means more time on Predictoor, including helping people build better predictoors and traders

**Therefore I recommend: option 2: fix just "(a) measure is too low", at least for now**

**Comment by trentmc** [comment]
### Plots for (a), with status quo measure of nmse
```
    # values taken from Predict-ETH round 7, see https://rb.gy/2bzw9
    # rank1 is first place, rank2 is second-place, rank3 third-place.
    # rank83 is 83rd place, the lowest-ranked for nmses < 1.0 (in round 7)
```
![1](https://github.com/oceanprotocol/df-py/assets/5305452/cda89d2d-d23c-4014-9582-c57adec60cb6)
![2](https://github.com/oceanprotocol/df-py/assets/5305452/407c0911-8574-47f9-9145-cb2f7e36b2b5)
![3](https://github.com/oceanprotocol/df-py/assets/5305452/c21976e2-b05c-4498-b796-16cc25944a8e)
![83](https://github.com/oceanprotocol/df-py/assets/5305452/ab86c4b0-2d6c-4b9b-a01e-815623f66659)

**Comment by trentmc** [comment]
### Plots for (a), with new measure of nmse

New measure of nmse scales CEX values and predicted values such that:
- CEX values are in range [0.0, 1.0]
- predicted values follow the same scaling factors

Setup:
- Like before
- Except with new measure of mnmse

Results:
- See images below

Analysis:
- Now, all four nmses look sane. The first ones are 10% - 20%, which is about right. And the rank-83 one is super-high (about 900%) which makes sense too. 

Conclusion:
- Ship it:)

![new1](https://github.com/oceanprotocol/df-py/assets/5305452/7fc6ccd3-d848-4926-b278-1c9d03e8ae15)
![new2](https://github.com/oceanprotocol/df-py/assets/5305452/4835db94-4dc5-4d55-9224-ff27b0b2f496)
![new3](https://github.com/oceanprotocol/df-py/assets/5305452/ed7bd90c-c297-4b28-b380-02fe301a4278)
![new83](https://github.com/oceanprotocol/df-py/assets/5305452/c287cc86-f9c7-4fe7-9887-95ddff734201)
