### ISSUE TITLE
Support predictoor assets

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#715]
### Background

Right now predictoor assets are being filtered out from Volume DF because they don't exist on Aquarius.

Note: df-py already [uses Aquarius](https://github.com/search?q=repo%3Aoceanprotocol%2Fdf-py%20aquarius&type=code)

### DoD
- Make the data "there". Options:
  1. Use a json file to hardcode metadata and predictoor contract addresses. Similar to [list-purgatory](https://github.com/oceanprotocol/list-purgatory)
  2. Get the contract addresses from subgraph using the OPF publisher address.
  3. Ensure the assets _are_ in Aquarius
- Update df-py to dynamically read and update the available assets array in volsym/allocations etc.

### Related

It's not urgent, but at some point it might be nice to support Predictoor assets inside Ocean Market. See [pdr-private#39](https://github.com/oceanprotocol/pdr-private/issues/39)

**Comment by trentmc** [comment]
I tweaked the description a bit, and laid out the options as candidates.

I added a third candidate: Ensure the assets _are_ in Aquarius.

@trizin what's stopping the assets from being in Aquarius right now?

**Comment by trentmc** [comment]
Makes sense. OK. That rules out option iii for now.

What's your thoughts on options i vs ii? ii seems simpler, especially wrt maintenance.
