### ISSUE TITLE
[predictoor] Update prediction subgraph model to include stake amount

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#720]
Add a new field "stake_amt" into Prediction model.
Update subgraph query to get this field while calculating predictions.

Why: then this data is available for the future, in case we find it useful

**Comment by trentmc** [comment]
Why is this in df-py? If it's for Predictoor DF, you don't need it. All you need to do is see the $ that each Predictoor made in the most recent week, and pay them pro rata
