### ISSUE TITLE
Inaccurate distribution of gas costs across the assets

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#737]
There is an error in the volume calculation for gas in transactions that involve multiple assets. Presently, the calculation incorrectly aggregates the total gas used for the entire transaction and assigns it solely to the first asset detected. Subsequent assets within the same transaction do not have the gas cost attributed to them, as the code includes a check to prevent the transaction hex from being accounted for more than once in the gas calculation. This results in an inaccurate distribution of gas costs across the assets.

**Comment by trentmc** [comment]
Good catch! I'm guessing that it (incorrectly) assumed a tx only involved one asset.

**Comment by calina-c** [comment]
Could #702 be related?
