### ISSUE TITLE
Improved dftool commands for DF-FE workflows

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-py#740]
### Challenges with DF-FE workflows
Right now, there are various tests and scenarios that we can't test effectively and are having to rely on bug reports to fix them.

It's nearly impossible for us to recreate these scenarios because:
- We can't simulate multiple rounds easily
- Recreating a state that enables us to claim multiple rounds is hard to reproduce
- Recreating a state that requires us to test if withdrawing funds or anything relating to locks are working, is hard to reproduce

### Towards a solution
It would help if there were helper functions that:
1. Mocks accounts locking + allocating + consuming datasets over an epoch
2. Updates epoch markers and distributes rewards based on passive/active DF

### DoD
- [ ] FE Devs are able to easily sim rounds and rewards
- [ ] FE Devs are able to easily recreate edge cases by expanding these dev functions and reproduce these in the FE so they can be reproduced, fixed, and deployed

**Comment by KatunaNorbert** [comment]
CSVs are just a part of it. The app also uses contract and subgraph calls, so we would also need those updated to fully test.
Would be nice to have a few wallets set up for different use cases:
- 1. Locked for 1 month, participated in DF, has rewards
- 2. Locked for 2 months, participated in DF, has rewards, delegated to Account 1 for VolumeDF
Move chain forward with 5 weeks so Account 1 can withdraw.

I think this ones would be enough for now and covers most of the use cases.
