### ISSUE TITLE
Challenge DF65 is not still calculated for rewards

### ISSUE THREAD

**Issue by jkearins** [oceanprotocol/df-py#772]
Hi, the issue with epochs.json is now resolved:
https://github.com/oceanprotocol/df-web/issues/687

But Challenge DF65 is not still calculated for rewards.

**Comment by trentmc** [comment]
This is incorrect. DF64 just ended today (Nov 30), and DF65 is starting.

The article "Ocean Data Farming Series" has exact dates for each DF round. https://blog.oceanprotocol.com/ocean-data-farming-series-c7922f1d0e45

**Comment by jkearins** [comment]
Hm... According to link: 
`DF66 runs Nov 30–Dec 7 2023`
so DF66 is starting

**Comment by trentmc** [comment]
Thanks for catching my error. I just updated the comment. 

@KatunaNorbert can you look into this please? Eg what's holding back DF65 from being calculated?

**Comment by KatunaNorbert** [comment]
Yes, I'll try

**Comment by KatunaNorbert** [comment]
It looks like rewards are distributed, the data is created but df-sql is not updated with the new created data

**Comment by jkearins** [comment]
For your info, maybe it will help: sometimes, not very often, when I refresh the page https://df.oceandao.org/challenge-df
I see an error message in browser WebTools console: "Access to fetch at 'https://df-sql.oceandao.org/challenge/data' from origin 'https://df.oceandao.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."
