### ISSUE TITLE
Goerli connection fails the reward flow, remove Goerli

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-py#819]
Goerli connection fails the reward flow, remove Goerli

Goerli is used to read the vested values from the vesting contract.

Since Halving Vesting is not started yet, it's safe to remove until we deploy on another chain.

**Comment by trentmc** [comment]
Don't remove Goerli, replace it

**Comment by alexcos20** [comment]
remove it please, as it's being closed

**Comment by trentmc** [comment]
> remove it please, as it's being closed

We want to test it on _some_ test net
